import streamlit as st
from ultralytics import YOLO
import pandas as pd
from PIL import Image
import cv2
import numpy as np
import os

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="AI 8.0: YOLO Object Detection",
    page_icon="🤖",
    layout="wide"
)

# --- LOAD TRAINED MODEL ---
@st.cache_resource
def load_yolo_model():
    # Fulfills Requirement 2: Uses the trained 'best.pt' weights
    return YOLO("best.pt")

# --- SIDEBAR NAVIGATION ---
st.sidebar.title("YOLO Activity Sections")
menu = [
    "1. Dataset Preparation", 
    "2. Training Results & Metrics", 
    "3. Image Testing (Live Demo)", 
    "4. Comparative Analysis",
]
choice = st.sidebar.radio("Navigate to:", menu)

# ==========================================
# SECTION 1: DATASET PREPARATION
# ==========================================
if choice == "1. Dataset Preparation":
    st.title("📂 Dataset Preparation")
    st.write("### Research & Dataset Fundamentals")
    st.info("**Dataset Link:** [https://universe.roboflow.com/misis-awstf/corn-qza4n]")
    
    st.markdown("""
    The dataset was selected and formatted specifically for **YOLO object detection**. 
    As required by the instructions, the data is organized into three subsets:
    - **Training set:** Used for the model to learn features.
    - **Validation set:** Used to monitor performance during training.
    - **Testing set:** Unseen images used for the final evaluation.
    
    The dataset folder contains **image files**, **annotation labels (txt files)**, and a **`data.yaml`** configuration file defining the classes and paths.
    """)

# ==========================================
# SECTION 2: TRAINING RESULTS & METRICS
# ==========================================
elif choice == "2. Training Results & Metrics":
    st.title("📊 Training Results & Performance")
    st.write("Requirement 2: Record metrics including training loss, validation loss, precision, recall, and mAP.")

    # Try to load the CSV results generated by YOLO
    if os.path.exists("results.csv"):
        df = pd.read_csv("results.csv")
        df.columns = df.columns.str.strip() # Clean headers
        
        # Extract last epoch results
        final = df.iloc[-1]
        
        m1, m2, m3, m4, m5 = st.columns(5)
        m1.metric("Precision", f"{final['metrics/precision(B)']:.4f}")
        m2.metric("Recall", f"{final['metrics/recall(B)']:.4f}")
        m3.metric("mAP50", f"{final['metrics/mAP50(B)']:.4f}")
        m4.metric("Train Box Loss", f"{final['train/box_loss']:.4f}")
        m5.metric("Val Box Loss", f"{final['val/box_loss']:.4f}")
        
        with st.expander("View Full Recorded Metrics Table"):
            st.dataframe(df)
    else:
        st.warning("results.csv not found in repository. Showing placeholder metrics.")

    st.write("---")
    st.subheader("Training Progress Visuals (Requirement 5)")
    
    col_a, col_b = st.columns(2)
    with col_a:
        if os.path.exists("results.png"):
            st.image("results.png", caption="Loss and Performance Curves over 10 Epochs")
    with col_b:
        if os.path.exists("confusion_matrix.png"):
            st.image("confusion_matrix.png", caption="Confusion Matrix: Predicted vs. Actual")

# ==========================================
# SECTION 3: IMAGE TESTING (LIVE DEMO)
# ==========================================
elif choice == "3. Image Testing (Live Demo)":
    st.title("🖼️ Image Testing & Prediction")
    st.write("Requirement 3: Test the model on new/unseen images and display bounding boxes, labels, and confidence.")
    
    uploaded_file = st.file_uploader("Upload an Image", type=['jpg', 'jpeg', 'png'])
    
    if uploaded_file is not None:
        model = load_yolo_model()
        image = Image.open(uploaded_file)
        
        # Perform Detection
        results = model.predict(source=image, conf=0.25)
        
        col1, col2 = st.columns(2)
        with col1:
            st.subheader("Uploaded Image")
            st.image(image, use_column_width=True)
            
        with col2:
            st.subheader("Detection Result")
            # plot() handles boxes, labels, and confidence scores automatically
            res_plotted = results[0].plot()
            res_rgb = cv2.cvtColor(res_plotted, cv2.COLOR_BGR2RGB)
            st.image(res_rgb, caption="Output with Bounding Boxes", use_column_width=True)
            
            # Show Raw Detections
            st.write("**Detected Objects:**")
            for box in results[0].boxes:
                conf = float(box.conf[0])
                cls = int(box.cls[0])
                name = model.names[cls]
                st.write(f"- {name.capitalize()}: {conf:.2%} confidence")

# ==========================================
# SECTION 4: COMPARATIVE ANALYSIS
# ==========================================
elif choice == "4. Comparative Analysis":
    st.title("🧠 Comparative Analysis")
    st.write("Requirement 4: Answers to the analytical questions.")
    
    qa = {
        "1. What is object detection?": "Object detection is a computer vision task that identifies and locates objects within an image or video, determining both WHAT an object is (classification) and WHERE it is (localization).",
        "2. How does YOLO perform object detection?": "YOLO (You Only Look Once) predicts bounding boxes and class probabilities simultaneously in a single pass through the network, making it optimized for real-time speed.",
        "3. What is the role of a pre-annotated dataset?": "It serves as the ground truth. It provides the model with correct examples of object locations and labels so it can learn to recognize them accurately.",
        "4. What do Precision, Recall, and mAP measure?": "Precision: Accuracy of positive predictions. Recall: Ability to find all actual objects. mAP (mean Average Precision): The overall performance score across all classes.",
        "5. What challenges did you encounter during training?": "Challenges included high computational demand requiring GPU (T4) usage and the need for more epochs to improve the recall of smaller objects.",
        "6. How can object detection performance be improved?": "By increasing the dataset size, using data augmentation (rotations/flips), and increasing training epochs for better model convergence."
    }
    
    for q, a in qa.items():
        with st.expander(q):
            st.write(a)
